os: osx
osx_image: xcode10
language: swift
script: xcodebuild clean build test -scheme "CoreDataSimpleUserStorageSwift" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.0,name=iPhone 8" CODE_SIGNING_REQUIRED=NO
